server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    web: DEBUG

fastdep:
  shiro-jwt:
    filter: #shiro过滤规则
      admin:
        path: /getatt
        role: jwt # jwt为需要进行token校验
      getattr:
        path: /dis
        role: jwt
      img:
        path: /img
        role: jwt
      changedetail:
        path: /changedetail
        role: jwt
      changepwd:
        path: /changepwd
        role: jwt
      getuser:
        path: /getuser
        role: jwt
      visit:
        path: /visit
        role: jwt
      delete:
        path: /deleteuser
        role: jwt
      getallatt:
        path: /getallatt
        role: jwt
      adduser:
        path: /adduser
        role: jwt
      front:
        path: /login/**/** ,/code
        role: anon # anon为无需校验
    secret: "6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52" # jwt秘钥